(function() {var implementors = {};
implementors['flate2'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='flate2/writer/struct.DeflateEncoder.html' title='flate2::writer::DeflateEncoder'>EncoderWriter</a>&lt;W&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='flate2/writer/struct.DeflateDecoder.html' title='flate2::writer::DeflateDecoder'>DecoderWriter</a>&lt;W&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='flate2/writer/struct.GzEncoder.html' title='flate2::writer::GzEncoder'>EncoderWriter</a>&lt;W&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='flate2/writer/struct.ZlibEncoder.html' title='flate2::writer::ZlibEncoder'>EncoderWriter</a>&lt;W&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;W: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Writer.html' title='std::io::Writer'>Writer</a> for <a class='struct' href='flate2/writer/struct.ZlibDecoder.html' title='flate2::writer::ZlibDecoder'>DecoderWriter</a>&lt;W&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
