(function() {var implementors = {};
implementors['flate2'] = ["<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.DeflateEncoder.html' title='flate2::reader::DeflateEncoder'>EncoderReader</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.DeflateDecoder.html' title='flate2::reader::DeflateDecoder'>DecoderReader</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.GzEncoder.html' title='flate2::reader::GzEncoder'>EncoderReader</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.GzDecoder.html' title='flate2::reader::GzDecoder'>DecoderReader</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.ZlibEncoder.html' title='flate2::reader::ZlibEncoder'>EncoderReader</a>&lt;R&gt;","<a class='stability Unmarked' title='No stability level'></a>impl&lt;R: <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/std/io/trait.Reader.html' title='std::io::Reader'>Reader</a> for <a class='struct' href='flate2/reader/struct.ZlibDecoder.html' title='flate2::reader::ZlibDecoder'>DecoderReader</a>&lt;R&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
